
#foursquare key
client_id = "PSHKSG4VZSBSMDCRPQJOLDXXSF14XFCKDQQ2HIN21FQYW50I"
client_secret = "KPE4BWCM3IDX1QII3MEVGSIHM0CNXOJVIL4JJL1WNKLOSRRL"


# Don't change this
MAPBOX_TOKEN = "pk.eyJ1IjoicHJpbmNpcGxleiIsImEiOiJjam1taTE3dGowamRjM3FqcG50MGp0anEwIn0.XuaFZy4Tff6aTfjiQUdd9Q"